services:
    jam_jar:
        class: JamStorageBundle\Services\JamJarService
        arguments:
          - "@doctrine.orm.entity_manager"
          - "@clone"
    clone:
        class: JamStorageBundle\Services\CloneService